---
deployment:
  tasks:
    - export DEPLOYPATH="/home/ylcqhxpa/public_html/"
    - echo "[DEPLOY] Starting deploy to $DEPLOYPATH at $(date)"
    # Sync files efficiently and avoid copying unwanted items
    - /bin/rsync -a --delete \
        --exclude ".git" \
        --exclude ".cpanel.yml" \
        --exclude "README.md" \
        --exclude "**/*.md" \
        ./ "$DEPLOYPATH"
    # Ensure .htaccess is present if tracked
    - test -f .htaccess && /bin/cp -f .htaccess "$DEPLOYPATH" || true
    # Set safe permissions (directories 755, files 644)
    - /usr/bin/find "$DEPLOYPATH" -type d -exec chmod 755 {} \;
    - /usr/bin/find "$DEPLOYPATH" -type f -exec chmod 644 {} \;
    # Harden database config if it exists under public_html
    - test -f "$DEPLOYPATH/config/database.php" && chmod 600 "$DEPLOYPATH/config/database.php" || true
    - echo "[DEPLOY] Completed at $(date)"
