---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ylcqhxpa/public_html
    - echo "Starting deployment..."
    - /bin/cp -rf * $DEPLOYPATH/ 2>/dev/null || true  
    - /bin/cp -f .htaccess $DEPLOYPATH/ 2>/dev/null || true
    - /bin/rm -rf $DEPLOYPATH/.git 2>/dev/null || true
    - /bin/chmod -R 755 $DEPLOYPATH 2>/dev/null || true
    - /bin/chmod 644 $DEPLOYPATH/.htaccess 2>/dev/null || true
    - echo "Deployment completed successfully"
