---
deployment:
  tasks:
    - export DEPLOYPATH="/home/ylcqhxpa/public_html/"
    - /bin/mkdir -p "$DEPLOYPATH"
    - echo "[DEPLOY] TAR sync start $(date)" > "$DEPLOYPATH/deploy.log"
    - |
      /bin/tar -C . \
        --exclude ".git" \
        --exclude ".cpanel.yml" \
        --exclude "README.md" \
        --exclude "**/*.md" \
        --exclude "**/*.sh" \
        --exclude "**/*.bat" \
        --exclude "**/diag.php" \
        --exclude "**/diagnostic.php" \
        --exclude "**/test.php" \
        --exclude "**/phptest.php" \
        -cf - . | /bin/tar -C "$DEPLOYPATH" -xf -
    - test -f .htaccess && /bin/cp -f .htaccess "$DEPLOYPATH" || true
    - echo "[DEPLOY] Done $(date)" >> "$DEPLOYPATH/deploy.log"
