name: Deploy to Hostico via FTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Validate PHP files
        run: |
          find . -type f -name "*.php" -print0 | xargs -0 -I {} php -l "{}" | grep -v "No syntax errors detected" || echo "PHP syntax check completed"

      - name: Log deployment info
        run: |
          echo "Deploying commit: ${{ github.sha }}"
          echo "Deployment time: $(date)"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"

      # FTP Deploy - dezactivat temporar
      # Uncomment și configurează secretele: FTP_SERVER, FTP_USERNAME, FTP_PASSWORD
      # - name: FTP Deploy
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: ./
      #     server-dir: /public_html/
      #     exclude: |
      #       **/.git*
      #       **/.github/**
      #       **/.cpanel.yml
      #       **/.gitattributes
      #       **/.ftpignore
      #       **/*.md
      #       **/*.sh
      #       **/*.bat
      #       **/diag.php
      #       **/diagnostic.php
      #       **/test.php
      #       **/phptest.php
      #       **/manual-deploy.*
      #       **/deploy-production.*
      #     log-level: minimal
      
      - name: Build complete
        run: echo "✅ Build completed successfully! Configure FTP secrets to enable auto-deploy."
